title: Daniela Rosca
author: Daniela Rosca
google_analytics: UA-106857733-1
email: daniela.roshca@gmail.com
phone: +31 6 51 34 66 85
location: Amsterdam, Netherlands
description: > # this means to ignore newlines until "baseurl:"
  Visual artist challenging documentary topics.

baseurl: "" # the subpath of your site, e.g. /blog
instagram_username:
twitter_username:
github_username:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
include: [_pages]
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
